name: CI
on:
    workflow_dispatch:
    push:
        branches:
            - '*'
            - '!master'
    pull_request:
        branches:
            - master

jobs:
    test:
        name: Test on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            python-version: ['3.9', '3.10', '3.11', '3.12']
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}
          - uses: snok/install-poetry@v4
            with:
              version: '1.8.3'
          - run: poetry install
          - run: poetry run check
            env:
              API_BASE_URL: ${{ vars.TASTYTRADE_CERT_URL }}
              TASTYTRADE_LOGIN: ${{ secrets.TASTYTRADE_CERT_LOGIN }}
              TASTYTRADE_PASSWORD: ${{ secrets.TASTYTRADE_CERT_PASSWORD }}